import Head from 'next/head'
import styles from '../styles/Home.module.css'
import WebUIKitHeader from "../components/WebUIKitHeader";
import LotteryEntrance from "../components/LotteryEntrance";
import {useMoralis} from "react-moralis";

const supportedChains = ["31337", "5"]

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis()

  return (
    <div className={styles.container}>
      <Head>
        <title>Smart Contract Raffle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <WebUIKitHeader/>
        {  isWeb3Enabled ? (
            <div>
                {supportedChains.includes(parseInt(chainId).toString()) ? (
                    <div className="flex flex-row">
                        <LotteryEntrance/>
                    </div>
                ) : (
                    <div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
                )}
            </div>
        ) : (
            <div>Please connect to a Wallet</div>
        )}
      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
